theme: jekyll-theme-minimal
title: Library
github:
  is_user_page: false
  is_project_page: true
plugins:
  - jekyll-redirect-from

defaults:
  -
    scope:
      path: "class-notes/*"
    values:
      site_section: "Class Notes"
  -
    scope:
      path: "patterns/*"
    values:
      site_section: "Software Patterns"
